package JavaScript.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.ui.deleteBuildType

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the buildType with uuid = '9e10fdf6-ccd0-4260-8882-1dad18ea99be' (id = 'JavaScript_02InternetExplorer')
from your code and delete the patch script.
*/
deleteBuildType("9e10fdf6-ccd0-4260-8882-1dad18ea99be")

